export let titles = [
    "Lost Wanderer",
    "Campfire Keeper",
    "Mud Hut Architect",
    "Berry Forager",
    "Stone Age Settler",
    "Timber Tycoon",
    "Thatched Roof Engineer",
    "Village Visionary",
    "Granary Guardian",
    "Primitive Craftsman",
    "Town Planner",
    "Defensive Wall Designer",
    "Trade Route Founder",
    "Iron Age Innovator",
    "Bronze Smith",
    "Skilled Farmer",
    "River Valley Settler",
    "First City Founder",
    "Spear Warlord",
    "Early Empire Builder",
    "Kingdom Overseer",
    "Lumber Baron",
    "Masonry Master",
    "Siege Tactician",
    "Fortress Commander",
    "Castle Constructor",
    "Crop Rotation Genius",
    "Knights' Commander",
    "Cartography Pioneer",
    "Feudal Lord",
    "Renaissance Ruler",
    "Architectural Visionary",
    "Black Powder Strategist",
    "Scholarly Monarch",
    "Maritime Explorer",
    "Trade Guild Leader",
    "Steam Engine Inventor",
    "Industrial Planner",
    "Railroad Pioneer",
    "Expanding Sovereign",
    "Ironworks Magnate",
    "Urban Developer",
    "Textile Baron",
    "Scientific Reformer",
    "Mass Production Master",
    "Power Grid Architect",
    "Naval Fleet Commander",
    "Financial Mogul",
    "Steam Age Warlord",
    "Railroad Emperor",
    "Technological Visionary",
    "Aviation Pioneer",
    "National Leader",
    "Military Generalissimo",
    "Infrastructure Titan",
    "Strategic Diplomacy Master",
    "Skyscraper Sovereign",
    "Nuclear Age Innovator",
    "Global Trade Magnate",
    "World Power Strategist",
    "Cybernetic Architect",
    "AI Pioneer",
    "High-Speed Network Engineer",
    "Megacity Planner",
    "Space Exploration Advocate",
    "Energy Grid Dominator",
    "Quantum Computing Genius",
    "Superpower Commander",
    "Global Policy Architect",
    "World Economy Ruler",
    "Interplanetary Explorer",
    "Space Colony Governor",
    "Terraforming Visionary",
    "Mars Settlement Founder",
    "Galactic Trade Overlord",
    "Starship Fleet Admiral",
    "Deep Space Pioneer",
    "Dyson Sphere Architect",
    "Cosmic Federation Leader",
    "Space Empire Chancellor",
    "Hyperloop Constructor",
    "AI Civil Administrator",
    "Planetary Terraformer",
    "Lunar Colony Governor",
    "Multiplanetary CEO",
    "Interstellar Supply Chain Expert",
    "Orbital Defense Strategist",
    "Sentient AI Diplomat",
    "Post-Scarcity Economist",
    "Galactic Research Titan",
    "Dark Matter Engineer",
    "Wormhole Navigator",
    "Cosmic Energy Master",
    "Space-Time Architect",
    "Multiverse Diplomat",
    "Singularity Prophet",
    "Reality Shaper",
    "Grand Overseer of Civilizations",
    "Eternal Cosmic Emperor",
    "Supreme Galactic Sovereign",
    "Starborn Monarch",
    "Celestial Realm Architect",
    "Cosmic Dictator",
    "Lord of Intergalactic Order",
    "Dimensional Conqueror",
    "Eternal Light Bearer",
    "Quantum Overlord",
    "Architect of the Infinite",
    "Keeper of Celestial Harmony",
    "Universe Unifier",
    "Master of Planetary Balance",
    "Overseer of Cosmic Cycles",
    "Time Stream Commander",
    "Celestial Knowledge Bearer",
    "Divine Space Chancellor",
    "Multiversal Herald",
    "Omnipotent Architect",
    "Starborn Emperor",
    "Weaver of Reality",
    "Ascended Civilization Creator",
    "The One Above All",
    "Keeper of the Cosmic Code",
    "Architect of Destiny",
    "Originator of Civilizations",
    "Prime Guardian of Existence",
    "Unchallenged Ruler of Stars",
    "Absolute Power Incarnate",
    "Supreme Creator of Worlds",
    "Titan of Cosmic Evolution",
    "Omniversal Dictator",
    "Divine Architect of Order",
    "The Eternal Sovereign",
    "Ultimate Harbinger of Progress",
    "Beyond Time and Space",
    "All-Knowing Mastermind",
    "The Cosmic Codekeeper",
    "The Great Balance Holder",
    "Overlord of Celestial Constructs",
    "The Infinite Ruler",
    "Titan of All Creation",
    "Final Architect of Civilization",
    "Master of Eternal Expansion",
    "The Supreme Universe Shaper",
    "One with the Cosmos",
    "Unfathomable Lord of Order",
    "Keeper of Universal Consciousness",
    "Grand Ruler of All Dimensions",
    "Boundless Force of Progress",
    "The Absolute Apex of Civilization",
    "The Omniversal Overlord"
];